# Generated by Django 5.0.6 on 2024-05-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='image/')),
                ('Prod_Name', models.CharField(max_length=254)),
                ('Prod_price', models.IntegerField()),
                ('Prod_offer', models.CharField(max_length=254)),
                ('Prod_decription', models.TextField()),
                ('Prod_use', models.CharField(max_length=254)),
            ],
        ),
    ]
