# Generated by Django 5.0.6 on 2024-05-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='Image',
        ),
    ]
